_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "/content/drive/MyDrive/Kaggle/Sartorius/model/pretrained/swin_B/swin_B_384_22k.pth"
  PIXEL_MEAN: [128,128,128]
  PIXEL_STD: [13.235,13.235,13.235]
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  BACKBONE:
    NAME: "build_swint_fpn_backbone"
  SWINT:
    OUT_FEATURES: ["stage2", "stage3", "stage4", "stage5"]
  FPN:
    IN_FEATURES: ["stage2", "stage3", "stage4", "stage5"]
INPUT:
  FORMAT: "BGR"
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  WEIGHT_DECAY: 0.0001
  BASE_LR: 0.0001
  AMP:
    ENABLED: True
TEST:
  EVAL_PERIOD: 20000 

DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
